# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ceShiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JIHuoNiaoAdSDK'
  # Pods for ceShiDemo

  target 'ceShiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ceShiDemoUITests' do
    # Pods for testing
  end

end
